package com.sirma.itt.javacourse.common;

/**
 * The class {@link ConstantsChat} contains constants used in the classes of its project.
 */
public enum ConstantsChat {
	ConstantsChat() {
	};
	public static final String SUGGESTING_MESSAGE = "EnterNickname";
	public static final String CONNECT = "connect";
	public static final String PERMITTED_NICKNAME = "[\\w\\d!@#$%^&*()_+]{3,12}";
	public static final String EN = "en";
	public static final String US = "US";
	public static final String BG2 = "bg";
	public static final String BG = "BG";
	public static final String BULGARIAN = "Bulgarian";
	public static final String ENGLISH = "English";
	public static final String INVALID_NICKNAME_INFO = "Nickname can not contain [ or ] and must have 3 to 12 symbols.";
	public static final String INPUT_OUTPUT_FAIL = "A transfer operation is failed or interrupted.";
	public static final String NO_ACTIVE_CONNECTION = "There is no active connection.";
	public static final String LOCAL_HOST = "localhost";
	public static final String SERVER_STOPPED = "Server stopped.";
	public static final String END_REVERSING = ".";
	public static final String EMPTY_STRING = "";
	public static final String SEND_BUTTON_LABEL = "Connect";
	public static final String CLIENT_WINDOW_LABEL = "Client Connector";
	public static final String CLOSING_BRACKET = "] ";
	public static final String OPENING_BRACKET = "[";
	public static final String SEND = "send";
	public static final String DISCONNECT = "disconnect";
	public static final String SEND_BTN_NAME = "sendBtn";
	public static final String CHAT_APP_TITLE = "Chat App";
	public static final String CHAT_SERVER = "Chat Server";
	public static final String LINE_SEPARATOR = System.lineSeparator();
	public static final String STOP_THREAD = "Stop thread";
	public static final String COLON = ": ";
	public static final String USER_DISCONNECTED = "userDisconnected";
	public static final String USER_LIST = "userList";
	public static final String NEW_USER = "newUser";
	public static final String TEXT_MESSAGE = "textMessage";
	public static final String STOP_READING = "Stop reading";
	public static final String LEFT = " left.";
	public static final String CLIENT = "Client ";
	public static final String CONNECTED = " connected.";
	public static final String HH_MM_SS = "HH:mm:ss";
	public static final String ALREADY_EXISTS = " alreadyExists";
	public static final String EXISTENT_NICKNAME = "Existent nickname";
	public static final String YOU_ARE_CONNECTED = "You are connected.";
	public static final String SEND_BTN = "sendBtn";
	public static final String ERROR = "Error";
	public static final String EXISTING_NICKNAME = "<html><center>The nickname you entered already exists.<br>Try again.</center></html>";
	public static final String ACCEPT = "Accept";
	public static final String CHAT_BUNDLE = "ChatBundle";
	public static final String CLASS_NOT_CASTED = "The class could not be casted";
	public static final String DISCONNECTED = " disconnected.";
	public static final String STARTED = " started.";
	public static final String NEW_THREAD = "A new thread for ";
	public static final String SERVER_STOPPED2 = "serverStopped";
	public static final String WELCOME = "Welcome";
	public static final int TARGET_PORT = 2004;
	public static final int COMMUNICATION_BUTTON_WIDTH = 110;
	public static final int LIMIT_OF_CHARACTERS = 200;
	public static final int COMMUNICATION_COMPONENT_HEIGHT = 30;
	public static final int INPUT_TEXT_FIELD_WIDTH = 400;
	public static final int COMMUNICATION_WINDOW_HEIGHT = 480;
	public static final int COMMUNICATION_WINDOW_WIDTH = 660;
	public static final int LIST_OF_CLIENTS_HEIGHT = 200;
	public static final int LIST_OF_CLIENTS_WIDTH = 200;
	public static final int FIRST_COLUMN_COMPONENT = 10;
	public static final int FIRST_ROW_COMPONENT = 30;
	public static final int SECOND_ROW_COMPONENT = 80;
	public static final int THIRD_ROW_COMPONENT = 130;
	public static final int FOURTH_ROW_COMPONENT = 180;
	public static final int FIFTH_ROW_COMPONENT = 230;
	public static final int SIXTH_ROW_COMPONENT = 280;
	public static final int COMPONENT_HEIGHT = 40;
	public static final int COMPONENT_WIDTH = 390;
	public static final int WINDOW_X_POSITION = 100;
	public static final int CLIENT_WINDOW_Y_POSITION = 50;
	public static final int SERVER_WINDOW_Y_POSITION = 350;
	public static final int WINDOW_HEIGHT = 225;
	public static final int WINDOW_WIDTH = 415;
	public static final int LIST_HEIGHT = 190;
	public static final int SERVER_WINDOW_HEIGHT = 375;
	public static final int CONNECTION_WINDOW_HEIGHT = 275;
	public static final int FIRST_ROW_LABEL = -5;
}
